name: Build

on:
  push:
    tags:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2

      - name: Set node version to lts/hydrogen
        uses: actions/setup-node@v3
        with:
          node-version: lts/hydrogen
          cache: pnpm

      - name: Install
        run: pnpm i

      - name: Build
        run: pnpm run build

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/aliyundrive-rename.user.js
