name: Build

on:
  push:
    tags:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2

      - name: Set node version to lts/hydrogen
        uses: actions/setup-node@v3
        with:
          node-version: lts/hydrogen
          cache: pnpm

      - name: Install
        run: pnpm i

      - name: Build
        run: pnpm run build

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/aliyundrive-rename.user.js

      - name: Release Branch
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: build
          FOLDER: dist
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # GitHub will automatically add this - you don't need to bother getting a token
          MESSAGE: 'Build: ({sha}) {msg}' # The commit message
          TARGET_DIR: dist
